---
title: "NCBI convert"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
df <- read.csv("Redox.csv")
```

### epost/efetch
```{r Create GI vector, eval=FALSE, echo=FALSE}
###Use the epost/efetch functions written by Laura to pull maizegdb accessions from XML file
options(stringsAsFactors = FALSE)

require(reutils)
require(readr)
require(XML)

#get GI accessions
giAccessions<-df$Accession
#remove gi accessions with alphas AKA nonconvertible
giAccessions<-giAccessions[-grep(giAccessions, pattern = "[a-zA-Z]")]
```

```{r epost, efetch, eval=FALSE, echo=FALSE}
#if re-running this, delete old copy of efetch.txt from file first
#first, convert GI to UID
#because more than 500, need to use epost first
p <- epost(giAccessions, db = "protein")
#efetch genpept file format for each UID, save to text file (requirement for epost>500)
efetch(p, db="protein",retmode = "text", rettype="gp", outfile = "efetch.txt")
```

```{r UID vec, eval=FALSE, echo=FALSE}
#read in UID text
UIDVec<-read.delim(file="efetch.txt", header = FALSE)
#convert to vector
UIDVec<-UIDVec[,1]
#get gene IDs from full flat file
UIDVec2<-UIDVec[grep(UIDVec, pattern="GeneID")]
#gsub out "GeneID:" to get accession number
UIDVec2<-gsub(UIDVec2, pattern=".*:", replacement = "")
#check that there is a UID for each GI
length(UIDVec2)==length(giAccessions)
```
```{r}
df2 <- unique(data.frame("GI"=as.numeric(as.character(giAccessions)), "Entrez"=as.numeric(UIDVec2)))
```
```{r}
df3 <- merge.data.frame(df, df2, by.x = "Accession", by.y = "GI")
```
```{r}
nrow(df)
nrow(df2)
nrow(df3)
```


